version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - API_KEY_GEMINI=${API_KEY_GEMINI}
      - API_KEY_EXA=${API_KEY_EXA}
      - API_KEY_TMDB=${API_KEY_TMDB}
