services:
  - type: web
    name: recommendation-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn recommendation_api:app --host 0.0.0.0 --port $PORT
    buildFilter:
      paths:
        - api/**
    envVars:
      - key: API_KEY_GEMINI
        sync: false
      - key: API_KEY_EXA
        sync: false
      - key: API_KEY_TMDB
        sync: false
      - key: CLIENT_API_KEY
        sync: false  # Gere uma chave forte e adicione no dashboard do Render
